<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Incident Report Generator</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        #output {
            white-space: pre-wrap;
            background: #f8f9fa;
            padding: 20px;
            margin-top: 20px;
            border: 1px solid #ccc;
        }
    </style>
</head>
<body>
<div class="container mt-5">
    <h3 class="mb-4">Incident Report Generator</h3>
    <form id="reportForm">
        <div class="mb-3"><label>Subject</label><input type="text" class="form-control" name="subject" required></div>
        <div class="mb-3"><label>Date and Time</label><input type="text" class="form-control" name="dt" required></div>
        <div class="mb-3"><label>Location</label><input type="text" class="form-control" name="location" required></div>
        <div class="mb-3"><label>Details of the Event</label><textarea class="form-control" name="details" rows="4" required></textarea></div>
        <div class="mb-3"><label>Captured Personnel</label><textarea class="form-control" name="captured" rows="2"></textarea></div>
        <div class="mb-3"><label>Recovery List</label><textarea class="form-control" name="recovery" rows="2"></textarea></div>
        <div class="mb-3"><label>Action Taken</label><textarea class="form-control" name="action" rows="2"></textarea></div>
        <div class="mb-3"><label>Report Generated By</label><input type="text" class="form-control" name="generated_by" required></div>
        <button type="submit" class="btn btn-primary">Generate Report</button>
        <button type="button" class="btn btn-secondary ms-2" onclick="copyToClipboard()">Copy to Clipboard</button>
    </form>

    <div id="output"></div>
</div>

<script>
    function formatAsBulletPoints(input) {
        const lines = input.split("\n").filter(line => line.trim() !== "");
        return lines.map((line, i) => `${String.fromCharCode(97 + i)}. ${line.trim()}`).join("\n");
    }

    document.getElementById("reportForm").addEventListener("submit", function (e) {
        e.preventDefault();
        const data = Object.fromEntries(new FormData(e.target).entries());

        const formattedDetails = formatAsBulletPoints(data.details);
        const formattedCaptured = formatAsBulletPoints(data.captured);
        const formattedRecovery = formatAsBulletPoints(data.recovery);
        const formattedAction = formatAsBulletPoints(data.action);

        const text = `Assalamu Alaikum Sir,

Incident Report: "*${data.subject}*"

1.  *Dt and Time:* ${data.dt}

2.  *Loc:* ${data.location}

3.  *Details of the Event:*

${formattedDetails}

4.  *Captured:*

${formattedCaptured}

5.  *Recovered Items:*

${formattedRecovery}

6.  *Act Taken:*

${formattedAction}

For your kind info Sir.

Regards
${data.generated_by}`;

        document.getElementById("output").textContent = text;
    });

    function copyToClipboard() {
        const text = document.getElementById("output").textContent;
        navigator.clipboard.writeText(text).then(() => {
            alert("Copied to clipboard!");
        });
    }
</script>
</body>
</html>
